// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.22.2
// source: game.op.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpCode 操作符定义
type OpCode int32

const (
	OpCode_None         OpCode = 0 // 心跳包占用
	OpCode_Op_C2S_Login OpCode = 1
	OpCode_Op_S2C_Login OpCode = 2
	OpCode_Op_C2S_Say   OpCode = 3
	OpCode_Op_S2C_Say   OpCode = 4
	OpCode_Op_S2S_Hi    OpCode = 5
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0: "None",
		1: "Op_C2S_Login",
		2: "Op_S2C_Login",
		3: "Op_C2S_Say",
		4: "Op_S2C_Say",
		5: "Op_S2S_Hi",
	}
	OpCode_value = map[string]int32{
		"None":         0,
		"Op_C2S_Login": 1,
		"Op_S2C_Login": 2,
		"Op_C2S_Say":   3,
		"Op_S2C_Say":   4,
		"Op_S2S_Hi":    5,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_game_op_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_game_op_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_game_op_proto_rawDescGZIP(), []int{0}
}

var File_game_op_proto protoreflect.FileDescriptor

var file_game_op_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x2a, 0x65, 0x0a, 0x06, 0x4f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x70, 0x5f, 0x43, 0x32,
	0x53, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x70, 0x5f,
	0x53, 0x32, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4f,
	0x70, 0x5f, 0x43, 0x32, 0x53, 0x5f, 0x53, 0x61, 0x79, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x4f,
	0x70, 0x5f, 0x53, 0x32, 0x43, 0x5f, 0x53, 0x61, 0x79, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x4f,
	0x70, 0x5f, 0x53, 0x32, 0x53, 0x5f, 0x48, 0x69, 0x10, 0x05, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_op_proto_rawDescOnce sync.Once
	file_game_op_proto_rawDescData = file_game_op_proto_rawDesc
)

func file_game_op_proto_rawDescGZIP() []byte {
	file_game_op_proto_rawDescOnce.Do(func() {
		file_game_op_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_op_proto_rawDescData)
	})
	return file_game_op_proto_rawDescData
}

var file_game_op_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_op_proto_goTypes = []interface{}{
	(OpCode)(0), // 0: pb.OpCode
}
var file_game_op_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_op_proto_init() }
func file_game_op_proto_init() {
	if File_game_op_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_op_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_op_proto_goTypes,
		DependencyIndexes: file_game_op_proto_depIdxs,
		EnumInfos:         file_game_op_proto_enumTypes,
	}.Build()
	File_game_op_proto = out.File
	file_game_op_proto_rawDesc = nil
	file_game_op_proto_goTypes = nil
	file_game_op_proto_depIdxs = nil
}
