// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.22.2
// source: gameserver.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// C2S_Ping 客户端向服务器发送心跳
type C2S_Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TickTime int64 `protobuf:"varint,1,opt,name=TickTime,proto3" json:"TickTime,omitempty"`
}

func (x *C2S_Ping) Reset() {
	*x = C2S_Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Ping) ProtoMessage() {}

func (x *C2S_Ping) ProtoReflect() protoreflect.Message {
	mi := &file_gameserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Ping.ProtoReflect.Descriptor instead.
func (*C2S_Ping) Descriptor() ([]byte, []int) {
	return file_gameserver_proto_rawDescGZIP(), []int{0}
}

func (x *C2S_Ping) GetTickTime() int64 {
	if x != nil {
		return x.TickTime
	}
	return 0
}

type S2C_Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OK bool `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
}

func (x *S2C_Pong) Reset() {
	*x = S2C_Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Pong) ProtoMessage() {}

func (x *S2C_Pong) ProtoReflect() protoreflect.Message {
	mi := &file_gameserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Pong.ProtoReflect.Descriptor instead.
func (*S2C_Pong) Descriptor() ([]byte, []int) {
	return file_gameserver_proto_rawDescGZIP(), []int{1}
}

func (x *S2C_Pong) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

// C2S_Login 登录服务器
type C2S_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *C2S_Login) Reset() {
	*x = C2S_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Login) ProtoMessage() {}

func (x *C2S_Login) ProtoReflect() protoreflect.Message {
	mi := &file_gameserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Login.ProtoReflect.Descriptor instead.
func (*C2S_Login) Descriptor() ([]byte, []int) {
	return file_gameserver_proto_rawDescGZIP(), []int{2}
}

func (x *C2S_Login) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *C2S_Login) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type S2C_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
}

func (x *S2C_Login) Reset() {
	*x = S2C_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Login) ProtoMessage() {}

func (x *S2C_Login) ProtoReflect() protoreflect.Message {
	mi := &file_gameserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Login.ProtoReflect.Descriptor instead.
func (*S2C_Login) Descriptor() ([]byte, []int) {
	return file_gameserver_proto_rawDescGZIP(), []int{3}
}

func (x *S2C_Login) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// C2S_Say 玩家通信
type C2S_Say struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actor int64  `protobuf:"varint,1,opt,name=Actor,proto3" json:"Actor,omitempty"`
	Word  string `protobuf:"bytes,2,opt,name=Word,proto3" json:"Word,omitempty"`
}

func (x *C2S_Say) Reset() {
	*x = C2S_Say{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Say) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Say) ProtoMessage() {}

func (x *C2S_Say) ProtoReflect() protoreflect.Message {
	mi := &file_gameserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Say.ProtoReflect.Descriptor instead.
func (*C2S_Say) Descriptor() ([]byte, []int) {
	return file_gameserver_proto_rawDescGZIP(), []int{4}
}

func (x *C2S_Say) GetActor() int64 {
	if x != nil {
		return x.Actor
	}
	return 0
}

func (x *C2S_Say) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type S2C_Say struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word string `protobuf:"bytes,1,opt,name=Word,proto3" json:"Word,omitempty"`
}

func (x *S2C_Say) Reset() {
	*x = S2C_Say{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Say) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Say) ProtoMessage() {}

func (x *S2C_Say) ProtoReflect() protoreflect.Message {
	mi := &file_gameserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Say.ProtoReflect.Descriptor instead.
func (*S2C_Say) Descriptor() ([]byte, []int) {
	return file_gameserver_proto_rawDescGZIP(), []int{5}
}

func (x *S2C_Say) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

// S2S_Hi 服务端玩家通信
type S2S_Hi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repeat string `protobuf:"bytes,1,opt,name=Repeat,proto3" json:"Repeat,omitempty"`
}

func (x *S2S_Hi) Reset() {
	*x = S2S_Hi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_Hi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_Hi) ProtoMessage() {}

func (x *S2S_Hi) ProtoReflect() protoreflect.Message {
	mi := &file_gameserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_Hi.ProtoReflect.Descriptor instead.
func (*S2S_Hi) Descriptor() ([]byte, []int) {
	return file_gameserver_proto_rawDescGZIP(), []int{6}
}

func (x *S2S_Hi) GetRepeat() string {
	if x != nil {
		return x.Repeat
	}
	return ""
}

var File_gameserver_proto protoreflect.FileDescriptor

var file_gameserver_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x26, 0x0a, 0x08, 0x43, 0x32, 0x53, 0x5f, 0x50, 0x69,
	0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x69, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x54, 0x69, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x1a,
	0x0a, 0x08, 0x53, 0x32, 0x43, 0x5f, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x4b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x4b, 0x22, 0x41, 0x0a, 0x09, 0x43, 0x32,
	0x53, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x1b, 0x0a,
	0x09, 0x53, 0x32, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x6b, 0x22, 0x33, 0x0a, 0x07, 0x43, 0x32,
	0x53, 0x5f, 0x53, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x57,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x57, 0x6f, 0x72, 0x64, 0x22,
	0x1d, 0x0a, 0x07, 0x53, 0x32, 0x43, 0x5f, 0x53, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x57, 0x6f,
	0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x57, 0x6f, 0x72, 0x64, 0x22, 0x20,
	0x0a, 0x06, 0x53, 0x32, 0x53, 0x5f, 0x48, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gameserver_proto_rawDescOnce sync.Once
	file_gameserver_proto_rawDescData = file_gameserver_proto_rawDesc
)

func file_gameserver_proto_rawDescGZIP() []byte {
	file_gameserver_proto_rawDescOnce.Do(func() {
		file_gameserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_gameserver_proto_rawDescData)
	})
	return file_gameserver_proto_rawDescData
}

var file_gameserver_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gameserver_proto_goTypes = []interface{}{
	(*C2S_Ping)(nil),  // 0: pb.C2S_Ping
	(*S2C_Pong)(nil),  // 1: pb.S2C_Pong
	(*C2S_Login)(nil), // 2: pb.C2S_Login
	(*S2C_Login)(nil), // 3: pb.S2C_Login
	(*C2S_Say)(nil),   // 4: pb.C2S_Say
	(*S2C_Say)(nil),   // 5: pb.S2C_Say
	(*S2S_Hi)(nil),    // 6: pb.S2S_Hi
}
var file_gameserver_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gameserver_proto_init() }
func file_gameserver_proto_init() {
	if File_gameserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gameserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_Say); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Say); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_Hi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gameserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gameserver_proto_goTypes,
		DependencyIndexes: file_gameserver_proto_depIdxs,
		MessageInfos:      file_gameserver_proto_msgTypes,
	}.Build()
	File_gameserver_proto = out.File
	file_gameserver_proto_rawDesc = nil
	file_gameserver_proto_goTypes = nil
	file_gameserver_proto_depIdxs = nil
}
