# 传输层协议，tcp, kcp
Network: "websocket"
# websocket时使用升级路径
WebsocketPath: "/ws"
# 每个连接的读超时(等于客户端心跳的超时)，秒为单位
ConnReadTimeout: 10
# 每个连接的写超时，秒为单位
ConnWriteTimeout: 5
# 连接成功后，多久未验证身份，则断开，秒为单位
ValidTimeout: 10
# 最大发送消息包大小
SendLimit: 1024
# 最大接收消息包大小
ReceiveLimit: 1024
# 心跳包限制数量, 每分钟不能超过的数量
HeartLimit: 100
# NATS的地址
NatsUrl: "nats://192.168.1.14:4222"
# 服务注册的前缀
Prefix: "/gameserver"
# 服务注册的Etcd地址
Etcd:
  - "192.168.1.14:2379"
# 是否开启TLS
TLS:
  CertFile: "../ssldata/server.cert"
  KeyFile: "../ssldata/server.key"