Logger:
  Level: "debug"
  Target: "user.service"
  Outpath: "./logs"

UserService:
  Prefix: "/services"
  Authentication:
    Mode: "TLS"
    CertFile: "../ssldata/cert.crt"
    KeyFile: "../ssldata/private.key"
  Etcd:
    - "192.168.1.9:2379"