package generate

var template = `// Code generated by codexctl. DO NOT EDIT.
package codex

type Code int

var codeMap = [{{length}}]int32{ {{code}} }
var msgMap = [{{length}}]string{ {{msg}} }

const (
{{keys}}
)

func (c Code) Code() int32 {
	return codeMap[int(c)]
}

func (c Code) Msg() string {
	return msgMap[int(c)]
}
`
